// Code generated by goctl. DO NOT EDIT.
// Source: identity.proto

package server

import (
	"context"

	"HorizonX/rpc/identity/identity"
	"HorizonX/rpc/identity/internal/logic"
	"HorizonX/rpc/identity/internal/svc"
)

type IdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	identity.UnimplementedIdentityServiceServer
}

func NewIdentityServiceServer(svcCtx *svc.ServiceContext) *IdentityServiceServer {
	return &IdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServiceServer) IssueJWT(ctx context.Context, in *identity.IssueJWTReq) (*identity.IssueJWTResp, error) {
	l := logic.NewIssueJWTLogic(ctx, s.svcCtx)
	return l.IssueJWT(in)
}

func (s *IdentityServiceServer) VerifyJWT(ctx context.Context, in *identity.VerifyJWTReq) (*identity.VerifyJWTResp, error) {
	l := logic.NewVerifyJWTLogic(ctx, s.svcCtx)
	return l.VerifyJWT(in)
}

func (s *IdentityServiceServer) DeclineJWT(ctx context.Context, in *identity.DeclineJWTReq) (*identity.DeclineJWTResp, error) {
	l := logic.NewDeclineJWTLogic(ctx, s.svcCtx)
	return l.DeclineJWT(in)
}
