package xerr

//grpc 的 err 对应的错误码其实就是一个 uint32 ， 我们自己定义错误用 uint32 然后在 rpc 的全局拦截器返回时候转成 grpc 的 err

const OK string = "OK"

// 通用错误码
const (
	SERVER_COMMON_ERROR     string = "SERVER_COMMON_ERROR"
	REQUEST_PARAM_ERROR     string = "REQUEST_PARAM_ERROR"
	UNAUTHORIZED            string = "You are not authorized to do this action"
	GENERAL_NOT_FOUND_ERROR string = "Resource not found"
	DB_ERROR                string = "DB_ERROR"
	DB_NOT_FOUND_ERROR      string = "DB_NOT_FOUND_ERROR"

	JWT_ISSUE_ERROR string = "JWT_ISSUE_ERROR"

	MQ_PUBLISH_ERROR     string = "MQ_PUBLISH_ERROR"
	JSON_UNMARSHAL_ERROR string = "JSON_UNMARSHAL_ERROR"
	UNA
)

// RPC模块细分错误码，如用户模块，订单模块等
// 用户模块
const (
	USER_PASSWORD_ERROR  string = "USER_PASSWORD_ERROR"
	USER_EXIST_ERROR     string = "USER_EXIST_ERROR"
	USER_NOT_FOUND_ERROR string = "USER_NOT_FOUND_ERROR"
)

// 订单模块
const (
	ORDER_CREATE_ERROR       string = "ORDER_CREATE_ERROR"
	ORDER_PLAN_NOT_FOUND            = "PLAN_NOT_FOUND"
	ORDER_VM_GROUP_NOT_FOUND        = "VM_GROUP_NOT_FOUND"
	ORDER_VM_IMAGE_NOT_FOUND        = "IMAGE_NOT_FOUND"
	ORDER_NOT_FOUND                 = "ORDER_NOT_FOUND"
	ORDER_HAS_PAID                  = "ORDER_HAS_BEEN_PAID"
	ORDER_STATUS_ERROR              = "ORDER_STATUS_ERROR"
	ORDER_ITEM_PARSE_ERROR          = "ORDER_ITEM_PARSE_ERROR"
)

// 支付模块
const (
	PAYMENT_METHOD_NOT_FOUND string = "PAYMENT_METHOD_NOT_FOUND"
	PAYMENT_CREATE_ERROR     string = "PAYMENT_CREATE_ERROR"
)

// VM 模块
const (
	HYPERVISOR_NODE_UNAVAILABLE string = "HYPERVISOR_NODE_UNAVAILABLE"
	OS_IMAGE_NOT_AVAILABLE      string = "OS_IMAGE_NOT_AVAILABLE"
	PROXMOX_VM_CREATE_FAILED    string = "PROXMOX_VM_CREATE_FAILED"
	PROXMOX_VM_FETCH_ERROR      string = "PROXMOX_VM_FETCH_ERROR"
	PROXMOX_VM_CONFIG_ERROR     string = "PROXMOX_VM_CONFIG_FAILED"
	IP_NO_AVAILABLE_ADDR_ERROR  string = "NO_AVAILABLE_IP_ADDRESS"
)

// SSH_KEY 模块
const (
	INVALID_SSH_KEY string = "INVALID_SSH_KEY"
)
