// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	hypervisorNodeFieldNames          = builder.RawFieldNames(&HypervisorNode{})
	hypervisorNodeRows                = strings.Join(hypervisorNodeFieldNames, ",")
	hypervisorNodeRowsExpectAutoSet   = strings.Join(stringx.Remove(hypervisorNodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	hypervisorNodeRowsWithPlaceHolder = strings.Join(stringx.Remove(hypervisorNodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	hypervisorNodeModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *HypervisorNode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*HypervisorNode, error)
		// Update(ctx context.Context, data *HypervisorNode) error
		Update(ctx context.Context, session sqlx.Session, data *HypervisorNode) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*HypervisorNode, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HypervisorNode, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HypervisorNode, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*HypervisorNode, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*HypervisorNode, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultHypervisorNodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	HypervisorNode struct {
		Id            int64  `db:"id"`
		GroupId       int64  `db:"group_id"`
		NodeName      string `db:"node_name"`
		Enable        int64  `db:"enable"`
		VirtType      string `db:"virt_type"`
		PveApi        string `db:"pve_api"` // eg: https://0.0.0.0:8006/api2/json
		PveTokenId    string `db:"pve_token_id"`
		PveSecret     string `db:"pve_secret"`
		PveNodeName   string `db:"pve_node_name"`
		VirtfusionApi string `db:"virtfusion_api"`
	}
)

func newHypervisorNodeModel(conn sqlx.SqlConn) *defaultHypervisorNodeModel {
	return &defaultHypervisorNodeModel{
		conn:  conn,
		table: "`hypervisor_node`",
	}
}

func (m *defaultHypervisorNodeModel) withSession(session sqlx.Session) *defaultHypervisorNodeModel {
	return &defaultHypervisorNodeModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`hypervisor_node`",
	}
}

func (m *defaultHypervisorNodeModel) Insert(ctx context.Context, session sqlx.Session, data *HypervisorNode) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, hypervisorNodeRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.GroupId, data.NodeName, data.Enable, data.VirtType, data.PveApi, data.PveTokenId, data.PveSecret, data.PveNodeName, data.VirtfusionApi)
	}
	return m.conn.ExecCtx(ctx, query, data.GroupId, data.NodeName, data.Enable, data.VirtType, data.PveApi, data.PveTokenId, data.PveSecret, data.PveNodeName, data.VirtfusionApi)
}

func (m *defaultHypervisorNodeModel) FindOne(ctx context.Context, id int64) (*HypervisorNode, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", hypervisorNodeRows, m.table)
	var resp HypervisorNode
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHypervisorNodeModel) Update(ctx context.Context, session sqlx.Session, data *HypervisorNode) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, hypervisorNodeRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.GroupId, data.NodeName, data.Enable, data.VirtType, data.PveApi, data.PveTokenId, data.PveSecret, data.PveNodeName, data.VirtfusionApi, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.GroupId, data.NodeName, data.Enable, data.VirtType, data.PveApi, data.PveTokenId, data.PveSecret, data.PveNodeName, data.VirtfusionApi, data.Id)
}

func (m *defaultHypervisorNodeModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultHypervisorNodeModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultHypervisorNodeModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*HypervisorNode, error) {

	builder = builder.Columns(hypervisorNodeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HypervisorNode

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHypervisorNodeModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HypervisorNode, error) {

	builder = builder.Columns(hypervisorNodeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HypervisorNode

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHypervisorNodeModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*HypervisorNode, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(hypervisorNodeRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*HypervisorNode

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultHypervisorNodeModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*HypervisorNode, error) {

	builder = builder.Columns(hypervisorNodeRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HypervisorNode

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHypervisorNodeModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*HypervisorNode, error) {

	builder = builder.Columns(hypervisorNodeRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HypervisorNode

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultHypervisorNodeModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultHypervisorNodeModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultHypervisorNodeModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHypervisorNodeModel) tableName() string {
	return m.table
}
