// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ipAddressFieldNames          = builder.RawFieldNames(&IpAddress{})
	ipAddressRows                = strings.Join(ipAddressFieldNames, ",")
	ipAddressRowsExpectAutoSet   = strings.Join(stringx.Remove(ipAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ipAddressRowsWithPlaceHolder = strings.Join(stringx.Remove(ipAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ipAddressModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *IpAddress) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*IpAddress, error)
		FindOneByIp(ctx context.Context, ip string) (*IpAddress, error)
		// Update(ctx context.Context, data *IpAddress) error
		Update(ctx context.Context, session sqlx.Session, data *IpAddress) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*IpAddress, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*IpAddress, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*IpAddress, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*IpAddress, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*IpAddress, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultIpAddressModel struct {
		conn  sqlx.SqlConn
		table string
	}

	IpAddress struct {
		Id         int64         `db:"id"`
		GroupId    int64         `db:"group_id"`
		InstanceId sql.NullInt64 `db:"instance_id"`
		Type       string        `db:"type"`
		Ip         string        `db:"ip"`
		Gateway    string        `db:"gateway"`
		Bridge     string        `db:"bridge"`
	}
)

func newIpAddressModel(conn sqlx.SqlConn) *defaultIpAddressModel {
	return &defaultIpAddressModel{
		conn:  conn,
		table: "`ip_address`",
	}
}

func (m *defaultIpAddressModel) withSession(session sqlx.Session) *defaultIpAddressModel {
	return &defaultIpAddressModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`ip_address`",
	}
}

func (m *defaultIpAddressModel) Insert(ctx context.Context, session sqlx.Session, data *IpAddress) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, ipAddressRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.GroupId, data.InstanceId, data.Type, data.Ip, data.Gateway, data.Bridge)
	}
	return m.conn.ExecCtx(ctx, query, data.GroupId, data.InstanceId, data.Type, data.Ip, data.Gateway, data.Bridge)
}

func (m *defaultIpAddressModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*IpAddress, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ipAddressRows, m.table)
	var resp IpAddress
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIpAddressModel) FindOneByIp(ctx context.Context, ip string) (*IpAddress, error) {
	var resp IpAddress
	query := fmt.Sprintf("select %s from %s where `ip` = ? limit 1", ipAddressRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, ip)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultIpAddressModel) Update(ctx context.Context, session sqlx.Session, newData *IpAddress) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ipAddressRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, newData.GroupId, newData.InstanceId, newData.Type, newData.Ip, newData.Gateway, newData.Bridge, newData.Id)
	}
	return m.conn.ExecCtx(ctx, query, newData.GroupId, newData.InstanceId, newData.Type, newData.Ip, newData.Gateway, newData.Bridge, newData.Id)
}

func (m *defaultIpAddressModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultIpAddressModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultIpAddressModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*IpAddress, error) {

	builder = builder.Columns(ipAddressRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*IpAddress

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultIpAddressModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*IpAddress, error) {

	builder = builder.Columns(ipAddressRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*IpAddress

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultIpAddressModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*IpAddress, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(ipAddressRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*IpAddress

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultIpAddressModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*IpAddress, error) {

	builder = builder.Columns(ipAddressRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*IpAddress

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultIpAddressModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*IpAddress, error) {

	builder = builder.Columns(ipAddressRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*IpAddress

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultIpAddressModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultIpAddressModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultIpAddressModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultIpAddressModel) tableName() string {
	return m.table
}
