// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sshKeysFieldNames          = builder.RawFieldNames(&SshKeys{})
	sshKeysRows                = strings.Join(sshKeysFieldNames, ",")
	sshKeysRowsExpectAutoSet   = strings.Join(stringx.Remove(sshKeysFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sshKeysRowsWithPlaceHolder = strings.Join(stringx.Remove(sshKeysFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sshKeysModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SshKeys) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*SshKeys, error)
		// Update(ctx context.Context, data *SshKeys) error
		Update(ctx context.Context, session sqlx.Session, data *SshKeys) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*SshKeys, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SshKeys, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SshKeys, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*SshKeys, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*SshKeys, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSshKeysModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SshKeys struct {
		Id      int64  `db:"id"`
		UserId  int64  `db:"user_id"`
		Name    string `db:"name"`
		Content string `db:"content"`
	}
)

func newSshKeysModel(conn sqlx.SqlConn) *defaultSshKeysModel {
	return &defaultSshKeysModel{
		conn:  conn,
		table: "`ssh_keys`",
	}
}

func (m *defaultSshKeysModel) withSession(session sqlx.Session) *defaultSshKeysModel {
	return &defaultSshKeysModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`ssh_keys`",
	}
}

func (m *defaultSshKeysModel) Insert(ctx context.Context, session sqlx.Session, data *SshKeys) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, sshKeysRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.UserId, data.Name, data.Content)
	}
	return m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Content)
}

func (m *defaultSshKeysModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*SshKeys, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sshKeysRows, m.table)
	var resp SshKeys
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSshKeysModel) Update(ctx context.Context, session sqlx.Session, data *SshKeys) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sshKeysRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.UserId, data.Name, data.Content, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Content, data.Id)
}

func (m *defaultSshKeysModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultSshKeysModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultSshKeysModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*SshKeys, error) {

	builder = builder.Columns(sshKeysRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SshKeys

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSshKeysModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SshKeys, error) {

	builder = builder.Columns(sshKeysRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SshKeys

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSshKeysModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SshKeys, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(sshKeysRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*SshKeys

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultSshKeysModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*SshKeys, error) {

	builder = builder.Columns(sshKeysRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SshKeys

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSshKeysModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*SshKeys, error) {

	builder = builder.Columns(sshKeysRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SshKeys

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSshKeysModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultSshKeysModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultSshKeysModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSshKeysModel) tableName() string {
	return m.table
}
