// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemPaymentMethodFieldNames          = builder.RawFieldNames(&SystemPaymentMethod{})
	systemPaymentMethodRows                = strings.Join(systemPaymentMethodFieldNames, ",")
	systemPaymentMethodRowsExpectAutoSet   = strings.Join(stringx.Remove(systemPaymentMethodFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	systemPaymentMethodRowsWithPlaceHolder = strings.Join(stringx.Remove(systemPaymentMethodFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	systemPaymentMethodModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *SystemPaymentMethod) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*SystemPaymentMethod, error)
		FindOneByName(ctx context.Context, name string) (*SystemPaymentMethod, error)
		FindOneByPath(ctx context.Context, path string) (*SystemPaymentMethod, error)
		// Update(ctx context.Context, data *SystemPaymentMethod) error
		Update(ctx context.Context, session sqlx.Session, data *SystemPaymentMethod) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*SystemPaymentMethod, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SystemPaymentMethod, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SystemPaymentMethod, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*SystemPaymentMethod, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*SystemPaymentMethod, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultSystemPaymentMethodModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SystemPaymentMethod struct {
		Id         int64  `db:"id"`
		Enable     int64  `db:"enable"`
		Type       string `db:"type"`
		Name       string `db:"name"`
		Path       string `db:"path"`
		Credential string `db:"credential"`
	}
)

func newSystemPaymentMethodModel(conn sqlx.SqlConn) *defaultSystemPaymentMethodModel {
	return &defaultSystemPaymentMethodModel{
		conn:  conn,
		table: "`system_payment_method`",
	}
}

func (m *defaultSystemPaymentMethodModel) withSession(session sqlx.Session) *defaultSystemPaymentMethodModel {
	return &defaultSystemPaymentMethodModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`system_payment_method`",
	}
}

func (m *defaultSystemPaymentMethodModel) Insert(ctx context.Context, session sqlx.Session, data *SystemPaymentMethod) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, systemPaymentMethodRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Enable, data.Type, data.Name, data.Path, data.Credential)
	}
	return m.conn.ExecCtx(ctx, query, data.Enable, data.Type, data.Name, data.Path, data.Credential)
}

func (m *defaultSystemPaymentMethodModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*SystemPaymentMethod, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemPaymentMethodRows, m.table)
	var resp SystemPaymentMethod
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindOneByName(ctx context.Context, name string) (*SystemPaymentMethod, error) {
	var resp SystemPaymentMethod
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", systemPaymentMethodRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindOneByPath(ctx context.Context, path string) (*SystemPaymentMethod, error) {
	var resp SystemPaymentMethod
	query := fmt.Sprintf("select %s from %s where `path` = ? limit 1", systemPaymentMethodRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, path)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) Update(ctx context.Context, session sqlx.Session, newData *SystemPaymentMethod) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, systemPaymentMethodRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, newData.Enable, newData.Type, newData.Name, newData.Path, newData.Credential, newData.Id)
	}
	return m.conn.ExecCtx(ctx, query, newData.Enable, newData.Type, newData.Name, newData.Path, newData.Credential, newData.Id)
}

func (m *defaultSystemPaymentMethodModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*SystemPaymentMethod, error) {

	builder = builder.Columns(systemPaymentMethodRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SystemPaymentMethod

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SystemPaymentMethod, error) {

	builder = builder.Columns(systemPaymentMethodRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SystemPaymentMethod

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*SystemPaymentMethod, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(systemPaymentMethodRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*SystemPaymentMethod

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*SystemPaymentMethod, error) {

	builder = builder.Columns(systemPaymentMethodRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SystemPaymentMethod

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*SystemPaymentMethod, error) {

	builder = builder.Columns(systemPaymentMethodRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SystemPaymentMethod

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultSystemPaymentMethodModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultSystemPaymentMethodModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultSystemPaymentMethodModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSystemPaymentMethodModel) tableName() string {
	return m.table
}
