// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vmInstanceFieldNames          = builder.RawFieldNames(&VmInstance{})
	vmInstanceRows                = strings.Join(vmInstanceFieldNames, ",")
	vmInstanceRowsExpectAutoSet   = strings.Join(stringx.Remove(vmInstanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vmInstanceRowsWithPlaceHolder = strings.Join(stringx.Remove(vmInstanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	vmInstanceModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *VmInstance) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*VmInstance, error)
		// Update(ctx context.Context, data *VmInstance) error
		Update(ctx context.Context, session sqlx.Session, data *VmInstance) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*VmInstance, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmInstance, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmInstance, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*VmInstance, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*VmInstance, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultVmInstanceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VmInstance struct {
		Id               int64          `db:"id"`
		CreateTime       time.Time      `db:"create_time"`
		UpdateTime       time.Time      `db:"update_time"`
		Vmid             int64          `db:"vmid"`
		UserId           int64          `db:"user_id"`
		HypervisorNodeId int64          `db:"hypervisor_node_id"`
		Name             string         `db:"name"`
		DueDate          time.Time      `db:"due_date"`
		BillingCycle     string         `db:"billing_cycle"`
		Price            int64          `db:"price"`
		Status           string         `db:"status"`
		PveUserId        string         `db:"pve_user_id"`
		PveUserPassword  string         `db:"pve_user_password"`
		PlanId           int64          `db:"plan_id"`
		Vcpu             int64          `db:"vcpu"`
		Memory           int64          `db:"memory"`
		Disk             int64          `db:"disk"`
		Bandwidth        int64          `db:"bandwidth"`
		DataTransfer     int64          `db:"data_transfer"`
		Traffic          int64          `db:"traffic"`
		Ipv4             sql.NullString `db:"ipv4"`
		Ipv6             sql.NullString `db:"ipv6"`
	}
)

func newVmInstanceModel(conn sqlx.SqlConn) *defaultVmInstanceModel {
	return &defaultVmInstanceModel{
		conn:  conn,
		table: "`vm_instance`",
	}
}

func (m *defaultVmInstanceModel) withSession(session sqlx.Session) *defaultVmInstanceModel {
	return &defaultVmInstanceModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`vm_instance`",
	}
}

func (m *defaultVmInstanceModel) Insert(ctx context.Context, session sqlx.Session, data *VmInstance) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, vmInstanceRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Vmid, data.UserId, data.HypervisorNodeId, data.Name, data.DueDate, data.BillingCycle, data.Price, data.Status, data.PveUserId, data.PveUserPassword, data.PlanId, data.Vcpu, data.Memory, data.Disk, data.Bandwidth, data.DataTransfer, data.Traffic, data.Ipv4, data.Ipv6)
	}
	return m.conn.ExecCtx(ctx, query, data.Vmid, data.UserId, data.HypervisorNodeId, data.Name, data.DueDate, data.BillingCycle, data.Price, data.Status, data.PveUserId, data.PveUserPassword, data.PlanId, data.Vcpu, data.Memory, data.Disk, data.Bandwidth, data.DataTransfer, data.Traffic, data.Ipv4, data.Ipv6)
}

func (m *defaultVmInstanceModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*VmInstance, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vmInstanceRows, m.table)
	var resp VmInstance
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVmInstanceModel) Update(ctx context.Context, session sqlx.Session, data *VmInstance) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vmInstanceRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Vmid, data.UserId, data.HypervisorNodeId, data.Name, data.DueDate, data.BillingCycle, data.Price, data.Status, data.PveUserId, data.PveUserPassword, data.PlanId, data.Vcpu, data.Memory, data.Disk, data.Bandwidth, data.DataTransfer, data.Traffic, data.Ipv4, data.Ipv6, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Vmid, data.UserId, data.HypervisorNodeId, data.Name, data.DueDate, data.BillingCycle, data.Price, data.Status, data.PveUserId, data.PveUserPassword, data.PlanId, data.Vcpu, data.Memory, data.Disk, data.Bandwidth, data.DataTransfer, data.Traffic, data.Ipv4, data.Ipv6, data.Id)
}

func (m *defaultVmInstanceModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultVmInstanceModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultVmInstanceModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*VmInstance, error) {

	builder = builder.Columns(vmInstanceRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmInstance

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmInstanceModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmInstance, error) {

	builder = builder.Columns(vmInstanceRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmInstance

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmInstanceModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmInstance, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(vmInstanceRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*VmInstance

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultVmInstanceModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*VmInstance, error) {

	builder = builder.Columns(vmInstanceRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmInstance

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmInstanceModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*VmInstance, error) {

	builder = builder.Columns(vmInstanceRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmInstance

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmInstanceModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultVmInstanceModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultVmInstanceModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVmInstanceModel) tableName() string {
	return m.table
}
