// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vmPlanFieldNames          = builder.RawFieldNames(&VmPlan{})
	vmPlanRows                = strings.Join(vmPlanFieldNames, ",")
	vmPlanRowsExpectAutoSet   = strings.Join(stringx.Remove(vmPlanFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vmPlanRowsWithPlaceHolder = strings.Join(stringx.Remove(vmPlanFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	vmPlanModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *VmPlan) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VmPlan, error)
		// Update(ctx context.Context, data *VmPlan) error
		Update(ctx context.Context, session sqlx.Session, data *VmPlan) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*VmPlan, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmPlan, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmPlan, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*VmPlan, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*VmPlan, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultVmPlanModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VmPlan struct {
		Id                int64  `db:"id"`
		HypervisorGroupId int64  `db:"hypervisor_group_id"`
		Name              string `db:"name"`
		Enable            int64  `db:"enable"`
		Visible           int64  `db:"visible"`
		Stock             int64  `db:"stock"`
		Vcpu              int64  `db:"vcpu"`
		Memory            int64  `db:"memory"`
		Disk              int64  `db:"disk"`
		DataTransfer      int64  `db:"data_transfer"`
		Bandwidth         int64  `db:"bandwidth"`
		Ipv4Num           int64  `db:"ipv4_num"`
		Ipv6Num           int64  `db:"ipv6_num"`
		MonthlyPrice      int64  `db:"monthly_price"`
		QuarterlyPrice    int64  `db:"quarterly_price"`
		SemiAnnuallyPrice int64  `db:"semi_annually_price"`
		AnnuallyPrice     int64  `db:"annually_price"`
	}
)

func newVmPlanModel(conn sqlx.SqlConn) *defaultVmPlanModel {
	return &defaultVmPlanModel{
		conn:  conn,
		table: "`vm_plan`",
	}
}

func (m *defaultVmPlanModel) withSession(session sqlx.Session) *defaultVmPlanModel {
	return &defaultVmPlanModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`vm_plan`",
	}
}

func (m *defaultVmPlanModel) Insert(ctx context.Context, session sqlx.Session, data *VmPlan) (sql.Result, error) {

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, vmPlanRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.HypervisorGroupId, data.Name, data.Enable, data.Visible, data.Stock, data.Vcpu, data.Memory, data.Disk, data.DataTransfer, data.Bandwidth, data.Ipv4Num, data.Ipv6Num, data.MonthlyPrice, data.QuarterlyPrice, data.SemiAnnuallyPrice, data.AnnuallyPrice)
	}
	return m.conn.ExecCtx(ctx, query, data.HypervisorGroupId, data.Name, data.Enable, data.Visible, data.Stock, data.Vcpu, data.Memory, data.Disk, data.DataTransfer, data.Bandwidth, data.Ipv4Num, data.Ipv6Num, data.MonthlyPrice, data.QuarterlyPrice, data.SemiAnnuallyPrice, data.AnnuallyPrice)
}

func (m *defaultVmPlanModel) FindOne(ctx context.Context, id int64) (*VmPlan, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vmPlanRows, m.table)
	var resp VmPlan
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVmPlanModel) Update(ctx context.Context, session sqlx.Session, data *VmPlan) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vmPlanRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.HypervisorGroupId, data.Name, data.Enable, data.Visible, data.Stock, data.Vcpu, data.Memory, data.Disk, data.DataTransfer, data.Bandwidth, data.Ipv4Num, data.Ipv6Num, data.MonthlyPrice, data.QuarterlyPrice, data.SemiAnnuallyPrice, data.AnnuallyPrice, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.HypervisorGroupId, data.Name, data.Enable, data.Visible, data.Stock, data.Vcpu, data.Memory, data.Disk, data.DataTransfer, data.Bandwidth, data.Ipv4Num, data.Ipv6Num, data.MonthlyPrice, data.QuarterlyPrice, data.SemiAnnuallyPrice, data.AnnuallyPrice, data.Id)
}

func (m *defaultVmPlanModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultVmPlanModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultVmPlanModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*VmPlan, error) {

	builder = builder.Columns(vmPlanRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmPlan

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmPlanModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmPlan, error) {

	builder = builder.Columns(vmPlanRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmPlan

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmPlanModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*VmPlan, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(vmPlanRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*VmPlan

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultVmPlanModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*VmPlan, error) {

	builder = builder.Columns(vmPlanRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmPlan

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmPlanModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*VmPlan, error) {

	builder = builder.Columns(vmPlanRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*VmPlan

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultVmPlanModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultVmPlanModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultVmPlanModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVmPlanModel) tableName() string {
	return m.table
}
