// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: identity.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	IssueJWT(ctx context.Context, in *IssueJWTReq, opts ...grpc.CallOption) (*IssueJWTResp, error)
	VerifyJWT(ctx context.Context, in *VerifyJWTReq, opts ...grpc.CallOption) (*VerifyJWTResp, error)
	DeclineJWT(ctx context.Context, in *DeclineJWTReq, opts ...grpc.CallOption) (*DeclineJWTResp, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) IssueJWT(ctx context.Context, in *IssueJWTReq, opts ...grpc.CallOption) (*IssueJWTResp, error) {
	out := new(IssueJWTResp)
	err := c.cc.Invoke(ctx, "/identity.IdentityService/IssueJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifyJWT(ctx context.Context, in *VerifyJWTReq, opts ...grpc.CallOption) (*VerifyJWTResp, error) {
	out := new(VerifyJWTResp)
	err := c.cc.Invoke(ctx, "/identity.IdentityService/VerifyJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeclineJWT(ctx context.Context, in *DeclineJWTReq, opts ...grpc.CallOption) (*DeclineJWTResp, error) {
	out := new(DeclineJWTResp)
	err := c.cc.Invoke(ctx, "/identity.IdentityService/DeclineJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility
type IdentityServiceServer interface {
	IssueJWT(context.Context, *IssueJWTReq) (*IssueJWTResp, error)
	VerifyJWT(context.Context, *VerifyJWTReq) (*VerifyJWTResp, error)
	DeclineJWT(context.Context, *DeclineJWTReq) (*DeclineJWTResp, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityServiceServer struct {
}

func (UnimplementedIdentityServiceServer) IssueJWT(context.Context, *IssueJWTReq) (*IssueJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueJWT not implemented")
}
func (UnimplementedIdentityServiceServer) VerifyJWT(context.Context, *VerifyJWTReq) (*VerifyJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyJWT not implemented")
}
func (UnimplementedIdentityServiceServer) DeclineJWT(context.Context, *DeclineJWTReq) (*DeclineJWTResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineJWT not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_IssueJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).IssueJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.IdentityService/IssueJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).IssueJWT(ctx, req.(*IssueJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifyJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.IdentityService/VerifyJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyJWT(ctx, req.(*VerifyJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeclineJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeclineJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeclineJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/identity.IdentityService/DeclineJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeclineJWT(ctx, req.(*DeclineJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueJWT",
			Handler:    _IdentityService_IssueJWT_Handler,
		},
		{
			MethodName: "VerifyJWT",
			Handler:    _IdentityService_VerifyJWT_Handler,
		},
		{
			MethodName: "DeclineJWT",
			Handler:    _IdentityService_DeclineJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}
