// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Email     string `json:"email" validate:"required,email"`
	Password  string `json:"password" validate:"required,min=8,max=20"`
	FirstName string `json:"first_name" validate:"required"`
	LastName  string `json:"last_name" validate:"required"`
	Country   string `json:"country" validate:"required,iso3166_1_alpha3"`
	Address   string `json:"address" validate:"required"`
	AffBy     int64  `json:"aff_by"`
}

type RegisterResp struct {
	Token string `json:"token"`
}
