// Code generated by goctl. DO NOT EDIT.
// Source: vm.proto

package server

import (
	"context"

	"HorizonX/rpc/vm/internal/logic"
	"HorizonX/rpc/vm/internal/svc"
	"HorizonX/rpc/vm/vm"
)

type VMServiceServer struct {
	svcCtx *svc.ServiceContext
	vm.UnimplementedVMServiceServer
}

func NewVMServiceServer(svcCtx *svc.ServiceContext) *VMServiceServer {
	return &VMServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VMServiceServer) DeployVMInstance(ctx context.Context, in *vm.DeployVMInstanceReq) (*vm.DeployVMInstanceResp, error) {
	l := logic.NewDeployVMInstanceLogic(ctx, s.svcCtx)
	return l.DeployVMInstance(in)
}
