// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package orderservice

import (
	"context"

	"HorizonX/rpc/order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateVMDeployOrderReq  = order.CreateVMDeployOrderReq
	CreateVMDeployOrderResp = order.CreateVMDeployOrderResp

	OrderService interface {
		// 创建虚拟机部署订单
		CreateVMDeployOrder(ctx context.Context, in *CreateVMDeployOrderReq, opts ...grpc.CallOption) (*CreateVMDeployOrderResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 创建虚拟机部署订单
func (m *defaultOrderService) CreateVMDeployOrder(ctx context.Context, in *CreateVMDeployOrderReq, opts ...grpc.CallOption) (*CreateVMDeployOrderResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateVMDeployOrder(ctx, in, opts...)
}
