// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"HorizonX/rpc/order/internal/logic"
	"HorizonX/rpc/order/internal/svc"
	"HorizonX/rpc/order/order"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建虚拟机部署订单
func (s *OrderServiceServer) CreateVMDeployOrder(ctx context.Context, in *order.CreateVMDeployOrderReq) (*order.CreateVMDeployOrderResp, error) {
	l := logic.NewCreateVMDeployOrderLogic(ctx, s.svcCtx)
	return l.CreateVMDeployOrder(in)
}
