// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	// 创建虚拟机部署订单
	CreateVMDeployOrder(ctx context.Context, in *CreateVMDeployOrderReq, opts ...grpc.CallOption) (*CreateVMDeployOrderResp, error)
	// 获取订单详情
	GetOrderDetailItem(ctx context.Context, in *GetOrderDetailItemReq, opts ...grpc.CallOption) (*GetOrderDetailItemResp, error)
	// 支付订单
	PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error)
	// 获取订单支付方式
	GetOrderPaymentMethod(ctx context.Context, in *GetOrderPaymentMethodReq, opts ...grpc.CallOption) (*GetOrderPaymentMethodResp, error)
	// 订单支付成功后的回调
	FullFillOrder(ctx context.Context, in *FullFillOrderReq, opts ...grpc.CallOption) (*FullFillOrderResp, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateVMDeployOrder(ctx context.Context, in *CreateVMDeployOrderReq, opts ...grpc.CallOption) (*CreateVMDeployOrderResp, error) {
	out := new(CreateVMDeployOrderResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/CreateVMDeployOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderDetailItem(ctx context.Context, in *GetOrderDetailItemReq, opts ...grpc.CallOption) (*GetOrderDetailItemResp, error) {
	out := new(GetOrderDetailItemResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrderDetailItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error) {
	out := new(PayOrderResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/PayOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderPaymentMethod(ctx context.Context, in *GetOrderPaymentMethodReq, opts ...grpc.CallOption) (*GetOrderPaymentMethodResp, error) {
	out := new(GetOrderPaymentMethodResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrderPaymentMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) FullFillOrder(ctx context.Context, in *FullFillOrderReq, opts ...grpc.CallOption) (*FullFillOrderResp, error) {
	out := new(FullFillOrderResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/FullFillOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	// 创建虚拟机部署订单
	CreateVMDeployOrder(context.Context, *CreateVMDeployOrderReq) (*CreateVMDeployOrderResp, error)
	// 获取订单详情
	GetOrderDetailItem(context.Context, *GetOrderDetailItemReq) (*GetOrderDetailItemResp, error)
	// 支付订单
	PayOrder(context.Context, *PayOrderReq) (*PayOrderResp, error)
	// 获取订单支付方式
	GetOrderPaymentMethod(context.Context, *GetOrderPaymentMethodReq) (*GetOrderPaymentMethodResp, error)
	// 订单支付成功后的回调
	FullFillOrder(context.Context, *FullFillOrderReq) (*FullFillOrderResp, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) CreateVMDeployOrder(context.Context, *CreateVMDeployOrderReq) (*CreateVMDeployOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVMDeployOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderDetailItem(context.Context, *GetOrderDetailItemReq) (*GetOrderDetailItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderDetailItem not implemented")
}
func (UnimplementedOrderServiceServer) PayOrder(context.Context, *PayOrderReq) (*PayOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderPaymentMethod(context.Context, *GetOrderPaymentMethodReq) (*GetOrderPaymentMethodResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderPaymentMethod not implemented")
}
func (UnimplementedOrderServiceServer) FullFillOrder(context.Context, *FullFillOrderReq) (*FullFillOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FullFillOrder not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateVMDeployOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMDeployOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateVMDeployOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CreateVMDeployOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateVMDeployOrder(ctx, req.(*CreateVMDeployOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderDetailItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderDetailItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderDetailItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrderDetailItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderDetailItem(ctx, req.(*GetOrderDetailItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_PayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/PayOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PayOrder(ctx, req.(*PayOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderPaymentMethodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrderPaymentMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderPaymentMethod(ctx, req.(*GetOrderPaymentMethodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_FullFillOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullFillOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).FullFillOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/FullFillOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).FullFillOrder(ctx, req.(*FullFillOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVMDeployOrder",
			Handler:    _OrderService_CreateVMDeployOrder_Handler,
		},
		{
			MethodName: "GetOrderDetailItem",
			Handler:    _OrderService_GetOrderDetailItem_Handler,
		},
		{
			MethodName: "PayOrder",
			Handler:    _OrderService_PayOrder_Handler,
		},
		{
			MethodName: "GetOrderPaymentMethod",
			Handler:    _OrderService_GetOrderPaymentMethod_Handler,
		},
		{
			MethodName: "FullFillOrder",
			Handler:    _OrderService_FullFillOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
