// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package server

import (
	"context"

	"HorizonX/rpc/payment/internal/logic"
	"HorizonX/rpc/payment/internal/svc"
	"HorizonX/rpc/payment/payment"
)

type PaymentServiceServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServiceServer
}

func NewPaymentServiceServer(svcCtx *svc.ServiceContext) *PaymentServiceServer {
	return &PaymentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServiceServer) CreatePayment(ctx context.Context, in *payment.CreatePaymentReq) (*payment.CreatePaymentResp, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}
